# Code checked into github points the app.yaml to the staging environment
# you should switch the app-id from STAGE to LIVE before deploying to production

# LIVE
# application: omega-keep-406
# version: 3

# STAGE
# application: elite-firefly-737
# version: 5

runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

# Endpoints handler
- url: /_ah/spi/.*
  script: services.register.application
# Cron job handler
- url: /crons/.*
  script: services.register_tasks.app
  login: admin
# Task job handler
- url: /tasks/.*
  script: services.register_tasks.app
  login: admin


libraries:
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0

builtins:
 - remote_api: on
